Cleaning data from https://www.kaggle.com/devinanzelmo/dota-2-matches

In [54]:
import pandas as pd
import numpy as np
import os

In [55]:
match = pd.read_csv("./data/match.csv")

In [56]:
match.head()

,match_id,start_time,duration,tower_status_radiant,tower_status_dire,barracks_status_dire,barracks_status_radiant,first_blood_time,game_mode,radiant_win,negative_votes,positive_votes,cluster
0,0,1446750112,2375,1982,4,3,63,1,22,True,0,1,155
1,1,1446753078,2582,0,1846,63,0,221,22,False,0,2,154
2,2,1446764586,2716,256,1972,63,48,190,22,False,0,0,132
3,3,1446765723,3085,4,1924,51,3,40,22,False,0,0,191
4,4,1446796385,1887,2047,0,0,63,58,22,True,0,0,156

In [57]:
os.listdir("./data")

['ability_ids.csv',
 'ability_upgrades.csv',
 'chat.csv',
 'cluster_regions.csv',
 'hero_names.csv',
 'item_ids.csv',
 'match.csv',
 'match_outcomes.csv',
 'objectives.csv',
 'patch_dates.csv',
 'players.csv',
 'player_ratings.csv',
 'player_time.csv',
 'purchase_log.csv',
 'teamfights.csv',
 'teamfights_players.csv',
 'test_labels.csv',
 'test_player.csv',
 'yasp_sample.json']

In [58]:
for col in match:
    print(col)

match_id
start_time
duration
tower_status_radiant
tower_status_dire
barracks_status_dire
barracks_status_radiant
first_blood_time
game_mode
radiant_win
negative_votes
positive_votes
cluster

In [53]:
# Identify column names
# This prints out column names in each datafile

dataset_names = os.listdir("./data")
for datafile in dataset_names:
    while True:
        if datafile == "yasp_sample.json":
            continue
        else:
            dataset = pd.read_csv("./data/{}".format(datafile))
            print("dataset:{}".format(datafile), dataset.columns)
            print("\n")
            break

dataset:ability_ids.csv Index(['ability_id', 'ability_name'], dtype='object')


dataset:ability_upgrades.csv Index(['ability', 'level', 'time', 'player_slot', 'match_id'], dtype='object')


dataset:chat.csv Index(['match_id', 'key', 'slot', 'time', 'unit'], dtype='object')


dataset:cluster_regions.csv Index(['cluster', 'region'], dtype='object')


dataset:hero_names.csv Index(['name', 'hero_id', 'localized_name'], dtype='object')


dataset:item_ids.csv Index(['item_id', 'item_name'], dtype='object')


dataset:match.csv Index(['match_id', 'start_time', 'duration', 'tower_status_radiant',
       'tower_status_dire', 'barracks_status_dire', 'barracks_status_radiant',
       'first_blood_time', 'game_mode', 'radiant_win', 'negative_votes',
       'positive_votes', 'cluster'],
      dtype='object')


dataset:match_outcomes.csv Index(['match_id', 'account_id_0', 'account_id_1', 'account_id_2',
       'account_id_3', 'account_id_4', 'start_time', 'parser_version', 'win',
       'rad'],
      dtype='object')


dataset:objectives.csv Index(['match_id', 'key', 'player1', 'player2', 'slot', 'subtype', 'team',
       'time', 'value'],
      dtype='object')


dataset:patch_dates.csv Index(['patch_date', 'name'], dtype='object')


dataset:players.csv Index(['match_id', 'account_id', 'hero_id', 'player_slot', 'gold',
       'gold_spent', 'gold_per_min', 'xp_per_min', 'kills', 'deaths',
       'assists', 'denies', 'last_hits', 'stuns', 'hero_damage',
       'hero_healing', 'tower_damage', 'item_0', 'item_1', 'item_2', 'item_3',
       'item_4', 'item_5', 'level', 'leaver_status', 'xp_hero', 'xp_creep',
       'xp_roshan', 'xp_other', 'gold_other', 'gold_death', 'gold_buyback',
       'gold_abandon', 'gold_sell', 'gold_destroying_structure',
       'gold_killing_heros', 'gold_killing_creeps', 'gold_killing_roshan',
       'gold_killing_couriers', 'unit_order_none',
       'unit_order_move_to_position', 'unit_order_move_to_target',
       'unit_order_attack_move', 'unit_order_attack_target',
       'unit_order_cast_position', 'unit_order_cast_target',
       'unit_order_cast_target_tree', 'unit_order_cast_no_target',
       'unit_order_cast_toggle', 'unit_order_hold_position',
       'unit_order_train_ability', 'unit_order_drop_item',
       'unit_order_give_item', 'unit_order_pickup_item',
       'unit_order_pickup_rune', 'unit_order_purchase_item',
       'unit_order_sell_item', 'unit_order_disassemble_item',
       'unit_order_move_item', 'unit_order_cast_toggle_auto',
       'unit_order_stop', 'unit_order_taunt', 'unit_order_buyback',
       'unit_order_glyph', 'unit_order_eject_item_from_stash',
       'unit_order_cast_rune', 'unit_order_ping_ability',
       'unit_order_move_to_direction', 'unit_order_patrol',
       'unit_order_vector_target_position', 'unit_order_radar',
       'unit_order_set_item_combine_lock', 'unit_order_continue'],
      dtype='object')


dataset:player_ratings.csv Index(['account_id', 'total_wins', 'total_matches', 'trueskill_mu',
       'trueskill_sigma'],
      dtype='object')


dataset:player_time.csv Index(['match_id', 'times', 'gold_t_0', 'lh_t_0', 'xp_t_0', 'gold_t_1',
       'lh_t_1', 'xp_t_1', 'gold_t_2', 'lh_t_2', 'xp_t_2', 'gold_t_3',
       'lh_t_3', 'xp_t_3', 'gold_t_4', 'lh_t_4', 'xp_t_4', 'gold_t_128',
       'lh_t_128', 'xp_t_128', 'gold_t_129', 'lh_t_129', 'xp_t_129',
       'gold_t_130', 'lh_t_130', 'xp_t_130', 'gold_t_131', 'lh_t_131',
       'xp_t_131', 'gold_t_132', 'lh_t_132', 'xp_t_132'],
      dtype='object')


dataset:purchase_log.csv Index(['item_id', 'time', 'player_slot', 'match_id'], dtype='object')


dataset:teamfights.csv Index(['match_id', 'start', 'end', 'last_death', 'deaths'], dtype='object')


dataset:teamfights_players.csv Index(['match_id', 'player_slot', 'buybacks', 'damage', 'deaths', 'gold_delta',
       'xp_end', 'xp_start'],
      dtype='object')


dataset:test_labels.csv Index(['match_id', 'radiant_win'], dtype='object')


dataset:test_player.csv Index(['match_id', 'account_id', 'hero_id', 'player_slot'], dtype='object')

KeyboardInterrupt:

In [59]:
# Examining hero_names.csv
# This datafile maps hero_id's to hero names

heroes = pd.read_csv("./data/hero_names.csv")
heroes.head()

                           name  hero_id  localized_name
0        npc_dota_hero_antimage        1       Anti-Mage
1             npc_dota_hero_axe        2             Axe
2            npc_dota_hero_bane        3            Bane
3     npc_dota_hero_bloodseeker        4     Bloodseeker
4  npc_dota_hero_crystal_maiden        5  Crystal Maiden

In [78]:
# players.csv determine team, heroes and players for each match
players = pd.read_csv("./data/players.csv")
players[:10]

,match_id,account_id,hero_id,player_slot,gold,gold_spent,gold_per_min,xp_per_min,kills,deaths,...,unit_order_glyph,unit_order_eject_item_from_stash,unit_order_cast_rune,unit_order_ping_ability,unit_order_move_to_direction,unit_order_patrol,unit_order_vector_target_position,unit_order_radar,unit_order_set_item_combine_lock,unit_order_continue
0,0,0,86,0,3261,10960,347,362,9,3,...,NaN,NaN,NaN,6.0,NaN,NaN,NaN,NaN,NaN,NaN
1,0,1,51,1,2954,17760,494,659,13,3,...,NaN,NaN,NaN,14.0,NaN,NaN,NaN,NaN,NaN,NaN
2,0,0,83,2,110,12195,350,385,0,4,...,NaN,NaN,NaN,17.0,NaN,NaN,NaN,NaN,NaN,NaN
3,0,2,11,3,1179,22505,599,605,8,4,...,1.0,NaN,NaN,13.0,NaN,NaN,NaN,NaN,NaN,NaN
4,0,3,67,4,3307,23825,613,762,20,3,...,3.0,NaN,NaN,23.0,NaN,NaN,NaN,NaN,NaN,NaN
5,0,4,106,128,476,12285,397,524,5,6,...,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN
6,0,0,102,129,317,10355,303,369,4,13,...,4.0,1.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN
7,0,5,46,130,2390,13395,452,517,4,8,...,NaN,NaN,NaN,4.0,110.0,NaN,NaN,NaN,NaN,NaN
8,0,0,7,131,475,5035,189,223,1,14,...,1.0,NaN,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN
9,0,6,73,132,60,17550,496,456,1,11,...,1.0,NaN,NaN,14.0,NaN,NaN,NaN,NaN,NaN,NaN

## Plan
hero_names: hero_id to name

match: match_id to radiant_win

players: 
    match_id to hero_id
    playerslot maps players to team: 0-4 radiant, 128-132 dire