In [1]:
import pandas as pd
import numpy as np
import os
import tensorflow as tf

In [4]:
# read combined dataset
df = pd.read_csv("./data/combined.csv")
df.head()
df.tail()
# 50000 matches - final splitting methodology not decided

,Unnamed: 0,name,hero_id,localized_name,match_id,account_id,player_slot,gold,gold_spent,gold_per_min,...,tower_status_dire,barracks_status_dire,barracks_status_radiant,first_blood_time,game_mode,radiant_win,negative_votes,positive_votes,cluster,win
0,402221,npc_dota_hero_rubick,86,Rubick,0,0,0,3261,10960,347,...,4,3,63,1,22,True,0,1,155,1
1,265414,npc_dota_hero_rattletrap,51,Clockwerk,0,1,1,2954,17760,494,...,4,3,63,1,22,True,0,1,155,1
2,390175,npc_dota_hero_treant,83,Treant Protector,0,0,2,110,12195,350,...,4,3,63,1,22,True,0,1,155,1
3,60411,npc_dota_hero_nevermore,11,Shadow Fiend,0,2,3,1179,22505,599,...,4,3,63,1,22,True,0,1,155,1
4,311776,npc_dota_hero_spectre,67,Spectre,0,3,4,3307,23825,613,...,4,3,63,1,22,True,0,1,155,1

In [41]:
df.train = df[:374972]
df.test = df[374972:]

# train contains match_id's 0 - 37499
# test contains match_id's 37500 - 49999

In [46]:
df.train.to_csv("./data/train.csv")
df.test.to_csv("./data/test.csv")